### ISSUE TITLE
Release app on F-Droid

### ISSUE THREAD

**Issue by koma-cute** [Utazukin/Ichaival#1]

**Comment by Utazukin** [comment]
I've submitted a merge [request](https://gitlab.com/fdroid/fdroiddata/merge_requests/4565), so assuming all goes well, it should get added whenever someone gets around to merging it.

**Comment by Asinin3** [comment]
@Utazukin Is there any reason why the version on F-Droid is old? Would be nice to see 0.7.0 and 0.6.0 on there.
