### ISSUE TITLE
Tag function suggestion.

### ISSUE THREAD

**Issue by gth7754125** [Utazukin/Ichaival#13]
Ichaival needs favorite tag function. maybe store the custom search string and add a rename function for the 'query string' can be a good way to implement it rather than derive  the tag function from LRR.(It only has 5 Favorite Tags). this way equal to implement the favorite Tag function and can implement the complex tag combination. In addition, it will not be limited in numbers and can search locally without query communication with LRR.

**Comment by Utazukin** [comment]
Since Lanraragi now lets you create your own categories, I'm marking this as fixed with version 0.8.0.
