### ISSUE TITLE
Opening gallery from bookmark causing crash.

### ISSUE THREAD

**Issue by wongsaraf** [Utazukin/Ichaival#15]
I never used the bookmark function before so I don't know if this related to the app or my Lanraragi server version.
I just updated my lanraragi version to nightly version today to fix the thumbnail size bugs.

Lanraragi version  v.0.6.9-EX (Nightly)
Ichaival version tested
7.5 Tablet
7.0 Phone

- Scenario 1
Adding gallery by holding the random button then opening the file from bookmark tab will cause the app to crash.

- Scenario 2
Open any gallery then bookmark it.
Open the same gallery from bookmark tab, no crash.
Close ichaival app then open it again.
Try to open that same gallery from bookmark tab, app crash.

Maybe the app crashed because when I open the gallery from bookmark tab, it doesn't extract the archive first?

**Comment by wongsaraf** [comment]
Tested with  v.0.6.9-EX  non-Nightly version, problem still persist.

I'm just reporting this bug, not really expecting it to be fixed as soon as possible.

**Comment by Utazukin** [comment]
I haven't had time to fully investigate this yet, but it appears to be related to the right to left reader setting. Disabling it should prevent the crashes for now.

**Comment by wongsaraf** [comment]
Can confirm, disabling Right to Left reader fix'd the problem.
