### ISSUE TITLE
HTTPS not working with Let's Encrypt

### ISSUE THREAD

**Issue by propeeves** [Utazukin/Ichaival#17]
I'm currently using LRR through a reverse proxy that uses certbot to make certs. It works when using a web browser, but on Ichaival it errors out with `java.security.cert.CertPathValidatorException:Trust anchor for certification path not found`

Might be related to https://forums.xamarin.com/discussion/91782/trust-anchor-for-certification-path-not-found from what I've searched about it.

**Comment by Utazukin** [comment]
I've tried running LRR through a reverse proxy using Apache and Let's Encrypt and was able to connect without issue.  According to [this answer](https://stackoverflow.com/questions/6825226/trust-anchor-not-found-for-android-ssl-connection#16302527), you may have a server set up issue.  What version of android are you using?

**Comment by propeeves** [comment]
Did further research and found I should've been using the `fullchain.pem` generated by certbot rather than `cert.pem` in my reverse proxy, so it was definitely on my end.

Only issue I'm having now is the API key not working while No-Fun mode is on - looking to see if it's also reverse proxy related
