### ISSUE TITLE
Pictures and thumbnails could not be loaded

### ISSUE THREAD

**Issue by uparrows** [Utazukin/Ichaival#18]
My lanraragi server version is 0.7.3 , ichaival version is 0.9 , and my phone is running android 10 , while click the read button , pictures could not be loaded , same for thumbnails .

![Screenshot_20201004-215512](https://user-images.githubusercontent.com/38988286/95017811-24f39d00-068e-11eb-9eac-334315ac2a05.jpg)
![Screenshot_20201004-215626](https://user-images.githubusercontent.com/38988286/95017815-27ee8d80-068e-11eb-86c4-2adc64635c04.jpg)

**Comment by Utazukin** [comment]
This can happen if the temp folder on the server gets emptied since attempting to get the image will fail because it no longer exists.  There's a "Force Refresh" option which will attempt to extract the archive again.  Although the reader should attempt that automatically, so I'll look into that.

**Comment by uparrows** [comment]
thanks ，but i've tried several times , still not working 。
![Screenshot_20201005-004528](https://user-images.githubusercontent.com/38988286/95021653-d69dc880-06a4-11eb-87e9-2043f97cfa52.jpg)
![Screenshot_20201005-004419](https://user-images.githubusercontent.com/38988286/95021657-dbfb1300-06a4-11eb-8aff-c2367244f76a.jpg)

**Comment by Utazukin** [comment]
Looks like I forgot to test with an api key.  This should be fixed in v0.9.1.
