### ISSUE TITLE
Using the Random feature causes a crash when it chooses an archive with no tags

### ISSUE THREAD

**Issue by crimsonraes** [Utazukin/Ichaival#19]
Ichaival version 0.9.1 (latest)
Lanraragi version 0.7.3 (latest)
Android version 10, OnePlus 5T

Tapping on the "RANDOM" button at the home page will crash the app if it selects an archive that doesn't have any tags. Opening the same archive from the home page or via search doesn't crash.
Tapping on "View Random Archive" from within an archive does not crash the app.
Tapping on "View Random Archive" from a page within an archive (via the wrench icon) does nothing; it doesn't crash, but it doesn't go to a random archive either.

Sometimes Random sends me to an archive with no tags and doesn't crash. I haven't figured out what's different with those archives, but I can confirm that Random doesn't cause a crash when it lands on an archive with tags.

**Comment by Utazukin** [comment]
The amount of tags shouldn't matter when picking an archive at random, but I did notice some issues that could cause a crash when using local search.  Are you using the local search option, and does this ever happen when the search field is empty?

**Comment by crimsonraes** [comment]
It happens if local search is on or off.

If I have a full tag name in the search field (i.e. "female:sole female", with quotation marks in the search), random doesn't crash at all, which is expected since the only galleries random picks from are those with tags. If I don't use a full tag name (english instead of "language:english"), it crashes whenever it picks a gallery with no tags since it matches "english" in the title of the gallery (i.e. Comic Title Here [English]).

**Comment by wongsaraf** [comment]
Same problem, but not related to tags.

Using random or manual open from the list cause crash on some gallery.
Brute forcing an a gallery by opening it several times fix the crash it but just for that one archive, every archive that cause crash need to be opened with that same method.

Disable/enabling volume key, left/right navigation, local search doesn't fix the crash.

tested on 0.9.1 and 0.9.2

Currently using version 0.8.0 and the crash stopped happening.

**Comment by crimsonraes** [comment]
Been using 0.9.5 for a good while, no crashes at all. Seems like the root issue's been fixed.
