### ISSUE TITLE
Change Subsampling or Add a better interpolation method

### ISSUE THREAD

**Issue by LawdStalker** [Utazukin/Ichaival#2]
Hi,
I noticed that some manga does not have a good quality when it's downscaled in the app, usually it is loaded with inferior quality compared to the webpage of lanraragi in the browser.

E.g.:
<details> 
  <summary>Page visualized in Ichaival: </summary>
 <img src="https://user-images.githubusercontent.com/50067181/56859614-e66b9600-6963-11e9-8a4c-65a960553807.png">
</details>
<details> 
  <summary>Page visualized in the Browser: </summary>
<strong>Better quality</strong>
 <img src="https://user-images.githubusercontent.com/50067181/56859658-609c1a80-6964-11e9-9dc3-4738a2453ccb.png">
</details>
<details> 
  <summary>Page visualized in <a href =https://github.com/nkanaev/bubble>Bubble</a> (A Comic Reader): </summary>
<strong>Optimal quality, i think</strong>
 <img src="https://user-images.githubusercontent.com/50067181/56859683-be306700-6964-11e9-9e53-9611127a76e6.png">
</details>
<details> 
  <summary>Original Image:</summary>
 <img src="https://user-images.githubusercontent.com/50067181/56859705-1bc4b380-6965-11e9-971e-d2b41345f836.png">
</details>

I think it would be nice if had a option to select a better method for downscaling or if it had a better method for default.

**Comment by Utazukin** [comment]
I've been looking into this, and I've been unable to reproduce it on the devices I have.  I've also tried using emulators running with 720x1280 resolution since that's the resolution of the screenshots, but bubble, chrome, and ichaival all display the same, or at least much more similar than what you're seeing.

What device and android version does this happen on?

**Comment by LawdStalker** [comment]
It doesn't happen with all manga, only some that apparently have fill patterns like this:
<details> 
  <summary>Original Image(Fill pattern):</summary>
 <img src="https://user-images.githubusercontent.com/50067181/60076334-ab84a500-96fd-11e9-9dd9-42cd2ec7c334.png">
</details>

> What device and android version does this happen on?

I'm using a Zenfone 5 A501 with Resurrection Remix (Android 7.1.2)

**Comment by atraholt** [comment]
I want to chime in and say this same display issue occurs for me on an Amazon Fire HD 8 (2018 model). It should be noted that this issue is also present in other readers such as Tachiyomi, so I assume there's either an issue with image scaling on the device or there's a shared library.

**Comment by gth7754125** [comment]
Similar problem when viewing manga. The Tachiyomi with Lanraragi Plugin looks better when dealing with it.
Maybe some improve way can be borrowed.
