### ISSUE TITLE
Error: Failed to extract Archive

### ISSUE THREAD

**Issue by WorldTeacher** [Utazukin/Ichaival#27]
I'm getting an error when trying to open a comic fron LRR using ichaival. The error is: Failed to extract Archive and occurs when trying to open any file ( all are .zip)

**Comment by WorldTeacher** [comment]
Apparently reinstalling the app multiple times  and clearing all caches through the phone settings fixed it for now

**Comment by Utazukin** [comment]
Closing due to lack of ability to reproduce and age of the issue.
