### ISSUE TITLE
Error loading more than one random file

### ISSUE THREAD

**Issue by EfronC** [Utazukin/Ichaival#37]
Hi, first of all, I want to thank for taking your time to add the option to load more than one random file. Now, I've been testing it, but is not working, when I try to load 1 file, it opens it like before, but if I set the file count to 2 or more, when i click the random button, the app crash, and says that the app has stopped. 

I'm not sure what might be the problem, since it doesn't launch any log that I can report, but just in help this helps, my LRR server is on version 0.8.3.

**Comment by Utazukin** [comment]
I believe I may have found the issue.  Do you have the local search option enabled?

**Comment by EfronC** [comment]
> I believe I may have found the issue. Do you have the local search option enabled?

Yes I have, I use it to reduce stress on my server, since is mounted on a RPi.
