### ISSUE TITLE
Ichaival unable to load items from Lanraragi 

### ISSUE THREAD

**Issue by Albireo6972** [Utazukin/Ichaival#41]
Been having this issue for a while now. I contributed it to issues on my server, which I have rebuilt about a month back. But sadly I am still getting this issue. I have copied the error log and will paste it here. No idea if this is just an "I'm an idiot" issue, but I thought it would be best to try and see if I could find some help. This is on the latest version, 1.5.0, been seeing this since older versions as well. 

Copy of error log:

java.lang.IllegalArgumentException: Initial result cannot be empty if items are present in data set.

-------Stack Trace --------

   i0.l$a.<init>(Unknown Source:48)
   i0.f1$f.a(Unknown Source:67)
   d3.p.i(Unknown Source:44)
   i0.f1.j(Unknown Source:18)
   i0.f1.f(Unknown Source:86)
   i0.z$e.z(Unknown Source:36)
   i0.z$e.C(Unknown Source:8)
   i0.z$e.i(Unknown Source:4)
   g4.b.b(Unknown Source:7)
   kotlinx.coroutines.l.e(Unknown Source:49)
   kotlinx.coroutines.j.g(Unknown Source:0)
   i0.z.f(Unknown Source:69)
   i0.a0$b.z(Unknown Source:155)
   n3.a.p(Unknown Source:11)
   kotlinx.coroutines.b1.run(Unknown Source:88)
   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
   java.lang.Thread.run(Thread.java:1012)
-------------------------------

----------- Cause ------------

--------------------------------

**Comment by Albireo6972** [comment]
So I tried an experiment, I deleted the instance of Lanraragi I had and rebuilt it. Ichaival then worked, up until about 20k items. Then it broke and kicked back a similar error:

java.lang.IllegalArgumentException: PositionalDataSource requires initial load size to be a multiple of page size to support internal tiling. loadSize 3, position 0, totalCount 4, pageSize 99

-------Stack Trace --------

   i0.l$a.e(Unknown Source:85)
   i0.f1$f.b(Unknown Source:6)
   i0.f1$f.a(Unknown Source:70)
   d3.p.i(Unknown Source:44)
   i0.f1.j(Unknown Source:18)
   i0.f1.f(Unknown Source:86)
   i0.z$e.z(Unknown Source:36)
   i0.z$e.C(Unknown Source:8)
   i0.z$e.i(Unknown Source:4)
   g4.b.b(Unknown Source:7)
   kotlinx.coroutines.l.e(Unknown Source:49)
   kotlinx.coroutines.j.g(Unknown Source:0)
   i0.z.f(Unknown Source:69)
   i0.a0$b.z(Unknown Source:155)
   n3.a.p(Unknown Source:11)
   kotlinx.coroutines.b1.run(Unknown Source:88)
   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
   java.lang.Thread.run(Thread.java:1012)
-------------------------------

----------- Cause ------------

--------------------------------


Overall I have about 60-70k items, and I know it works with some of the other programs for Android, but I really like this one. Is there a way to increase the time it takes to timeout? I am wondering if that may help.

**Comment by Utazukin** [comment]
Does this only happen when you search?  It seems like the app is unable to find all the matching archives in its own database.

**Comment by Albireo6972** [comment]
It happens when I load into the app. I will launch it, it will authenticate, then try to pull info from my instance of Lanraragi, and then error out. I was able to get it to talk after a full teardown and reconstruction of my instance. But it only lasted for a little while. It could be that it just does not understand some of the archive names, but I don't really understand the errors fully. If it helps, this happens on both the Docker and Windows installs of Lanraragi. I wanted to test both to make sure it was not just a one system vs the other issue.

**Comment by Utazukin** [comment]
I don't have a library large enough to reproduce this, but there have been several optimizations to handle syncing large libraries in 1.6.0 that may help with this.  The code the crash was in has also been completely replaced as it was using a deprecated library.

**Comment by Albireo6972** [comment]
Sorry for the delay, I am testing out the new build. I'll let you know how things look. Thank you for the update, and for working on the project.

Edit: hit the wrong button, and accidentally closed it, my apologies.

**Comment by Albireo6972** [comment]
![SmartSelect_20230405_142006_Ichaival](https://user-images.githubusercontent.com/46336030/230214082-abbccddb-848d-4211-a347-97f202a84586.gif)
It will now see that I have items, but only if I have new selected. When I do that, interesting things happen, I uploaded a gif with what I am seeing. For clarity, I am unable to select any files, it just goes down until it reaches 0. Then I have to clear the cache and data to get this result again.

**Comment by Utazukin** [comment]
Hmm, what it looks like is no entries are actually getting inserted into the local database.  Checking the new checkbox performs a search on the server.  Once we get those results, it attempts to get the matching archives in the local database by their ids.  Does pressing the refresh button do anything?  I can't think of any reason nothing would get inserted into the database without the app crashing during sync.

**Comment by Albireo6972** [comment]
I have no idea what I did, but it works now! Thank you for all the help, and I am very sorry for sending you through a wild goose chase for my issue, but I really appreciate it.
