### ISSUE TITLE
Ichaival doesn't open since new update

### ISSUE THREAD

**Issue by EfronC** [Utazukin/Ichaival#43]
I updated Ichaival yesterday from F-Droid to 1.6.0, and ever since it doesn't open, it tries to open, but closes immediately, and only a message appears saying "Ichaival has stopped" and if I keep trying to open, it changes to "Ichaival keeps stopping". 

Due to this behavior is that I can't get any kind of log of what's happening, and F-Droid doesn't let me rollback to 1.5.0 for some reason.

My LRR is running on 0.8.3, and Android is 7.1.1. Not sure if there is something else I need to provide that would be from help.

**Comment by Utazukin** [comment]
This is most likely due to an issue in older versions of android with some of the sqlite queries I was using.  It should be fixed in the next version with c037d05c07e9cbe4c78f7b8118f3cd5df4817e8c.
