### ISSUE TITLE
Not all pages are loaded when extracting / reading an archive

### ISSUE THREAD

**Issue by DanLabute** [Utazukin/Ichaival#46]
Ichaival 1.7.1
Android 14
LANraragi 0.9.0 running on Docker 24.0.7

When reading more than one book in a single session (ie: finishing one book, and then opening a new one), books after the first one often do not load all pages. For example, in the screenshots below I open a book in Ichaival. No errors are displayed, but the book reports only 13 pages in length, while the actual length of the book is 232 pages, confirmed in lanraragi itself.

Force Refresh does not remedy the issue
Clearing local cache / clear temp folder occasionally, but very rarely fixes the issue. Works maybe 1/10 times.

Not a whole lot of information to go on unfortunately, as no errors appear to have been generated. If there's any helpful logging or additional information I can provide, please let me know.

### Lanraragi Web
![lanraragi web](https://github.com/Utazukin/Ichaival/assets/5962891/6ecdd7b0-c122-4edf-a255-7722e8812339)

### Ichaival
![ichaival](https://github.com/Utazukin/Ichaival/assets/5962891/15a46fce-0d76-4215-aa81-b612a8843573)

**Comment by Utazukin** [comment]
There's two ways Ichaival gets the page count from an archive.  First is it gets it directly from the LRR database if it has it.  Second is the number of files returned when extracting the archive.  It's possible something went wrong the first time the archive was extracted, so Ichaival got the wrong count.  If the LRR web view is showing the correct number, I think resyncing should fix it.  Using LRR's "Rescan Archive Directory" option to generate page counts for each archive should also help.

**Comment by DanLabute** [comment]
I'll give your suggestions a try and report back, thank you!

**Comment by DanLabute** [comment]
Rescanning the archive directory and resyncing Ichaival appears to have resolved the issue. Thank you for your help!
