### ISSUE TITLE
Sorting archives list by date doesn't exist

### ISSUE THREAD

**Issue by wongsaraf** [Utazukin/Ichaival#47]
Ichaival version :  v1.7.2
Lanraragi version : 0.9.0
Tested on two devices with different android version

In the last year sorting by date filter menu doesn't exist anymore and only show blank tab.
Date_added tags already enabled and added to each archives.

![Untitled](https://github.com/Utazukin/Ichaival/assets/12886212/55f11adf-ee17-4aef-8372-60c707775992)

**Comment by Utazukin** [comment]
I believe this should be fixed in version 1.7.3.

**Comment by wongsaraf** [comment]
Updating to 1.7.3 fixed the problem, thank you.
