### ISSUE TITLE
Filter sidebar content is not displayed correctly

### ISSUE THREAD

**Issue by KaIKuxy** [Utazukin/Ichaival#48]
### Lanraragi: 0.9.0

Button is clickable, it's just that the content is not fully displayed in the sidebar

![Screenshot_2024-04-26-01-37-23-28_f9a53d114f493f45bd0fd61d6bbf3aea](https://github.com/Utazukin/Ichaival/assets/17746583/8910fc56-fd87-465c-b713-50625e2d319a)

**Comment by Utazukin** [comment]
This should be fixed in version 1.7.4.
