### ISSUE TITLE
Supporting local storage

### ISSUE THREAD

**Issue by Naudriel** [Utazukin/Ichaival#49]
Even though Lanraragi is a server application, can Ichaival have the option to look for the same content structure locally?

This can be useful for users who can't have the server running 24/7 but have sufficient local storage on their device.

**Comment by Solovertical** [comment]
This would be best, there is an implementation to select the local directory exists in [Kotatsu](https://github.com/KotatsuApp/Kotatsu) app. That can be helpful to give some idea about this feature, the only thing that app is missing is metadata for local.
