### ISSUE TITLE
The software takes a long time to open

### ISSUE THREAD

**Issue by Putarku** [Utazukin/Ichaival#50]
When the software is completely closed and reopened, it takes a long time to display. It may take 30 seconds to 1 minute. there are 40,000 comics on my server.

Can it be changed to display the first 30 or 50 works on the Lanraragi server first?

**Comment by Utazukin** [comment]
That's strange.  There's nothing in particular that should be slowing it down from a cold start.  The app will sync with the server every 24 hours or when the refresh button is pressed, but otherwise, it should only load what's visible on screen.

**Comment by Utazukin** [comment]
I'm not sure if this will help your issue, but there is a new option to change the amount of time before the app will automatically sync with the server on startup.  Setting this to -1 will disable automatic syncing, which should decrease the startup time since it won't sync each time.

**Comment by Putarku** [comment]
Yes, this is the effect I want. Now, when I open the software, the content can be displayed quickly. Since I usually upload comics about once a week, I can now choose to manually update, so I don't have to endure long synchronization times every time I open the software. Alternatively, the synchronization feature could be changed to work in the background, displaying the content from the last synchronization first and then syncing with the server in the background. This way, the user experience should also be improved.
