### ISSUE TITLE
[Feature Request] add joystick button for navigation and autoload next archive

### ISSUE THREAD

**Issue by krakerz** [Utazukin/Ichaival#53]
as the title said, is it possible to make joystick button for navigation ? for example, left and right, currently only button mapped to volume is working, while in reading page, as for in listing, the joystick navigation is worked as intended. Perfect Viewer is an example for this kind of navigation

also if it's possible to autoload the next archive, it would be good 👍 

*bluetooth controller

**Comment by Utazukin** [comment]
Controller support should be doable, but I'm not sure about autoloading.  There isn't really a concept of a "next" archive to automatically load in LRR.

**Comment by krakerz** [comment]
> Controller support should be doable, but I'm not sure about autoloading. There isn't really a concept of a "next" archive to automatically load in LRR.

after thinking it back, yeah the "hext" archieve is not exist in LRR, only "switch to next random archieve" is, RIP
hope the controller support will be implemented soon, (its been implemented in Lanreader for ios atleast)
thanks
