### ISSUE TITLE
Unsupported version (new version lanraragi out last week)

### ISSUE THREAD

**Issue by krakerz** [Utazukin/Ichaival#55]
![Screenshot_20240705-092040_Ichaival](https://github.com/Utazukin/Ichaival/assets/8030983/005cf5cc-d4f5-4ad2-8201-880103f15c38)
Since last week lanraragi have new version, I got this when I do clean install the app

**Comment by Utazukin** [comment]
Do you mean version 0.9.10? That's what I'm currently running, and I haven't noticed any issues.  What version of Android and Ichaival are you using?

**Comment by krakerz** [comment]
> Do you mean version 0.9.10? That's what I'm currently running, and I haven't noticed any issues. What version of Android and Ichaival are you using?

android 14 (GSI)
fdroid says 1.8.0
and yes, i'm using Version 0.9.10, "Dead Man Walking"

my case :
1. updated it from previous version via fdroid
2. connected to the server, but noticed something wrongs (no new archieve is listed there)
3. try to reconnect to the server by clear host settings and input it back
4. same result
5. then i do full clear data + cache / simply uninstalled the app
6. open the new version with fresh setup
7. attempt to connect to the server, and said as the screenshoot i attached in first post

you might want to check, if by clearing data / reinstall the app, will reproduce the issues?

**Comment by krakerz** [comment]
i finally have a chance with other phone (android 12)
its working fine ._.

tried to reinstall in my android 14 again
and noticed, it's auto corrected http:// to https:// by default
after forcing it to http://xxxx.local.id (my local domain for the server)
it's working as intended now, sorry for opening new issue without double crosscheck it 🙏
