### ISSUE TITLE
[Feature Request] Custom Request Headers in Settings

### ISSUE THREAD

**Issue by gustaavv** [Utazukin/Ichaival#57]
My LANraragi server is behind an Nginx instance with basic authentication.

To pass the basic auth, the request headers must contain:
```http
'Authorization': 'Basic XYZ'
```

So, It would be nice if users can set custom request headers in the Server section in settings. 

Thanks.

---

Given that you are using `Authorization` header to send api key, I recommend using [query string `?key=[API_KEY]`](https://sugoi.gitbook.io/lanraragi/advanced-usage/external-readers#:~:text=API_KEY) to pass the authentication of LANraragi. Otherwise, it will conflict with basic auth of Nginx.

```kotlin
private fun createServerConnection(url: String, method: String = "GET", body: RequestBody? = null) : Request {
    return with (Request.Builder()) {
        method(method, body)
        url(url)
        if (apiKey.isNotEmpty())
            addHeader("Authorization", apiKey)
        build()
    }
}
```

**Comment by Difegue** [comment]
The query string auth method is mostly meant for the OPDS feeds -- I wouldn't use it for an entire client.

**Comment by Utazukin** [comment]
Do you use both an api key and basic auth?  It should be simple enough to add the ability to use custom headers, and if an api key isn't defined, the extra Authorization header won't be added.

**Comment by gustaavv** [comment]
> Do you use both an api key and basic auth?

No, I don't. I don't intend to call the protect APIs from client. I just want Ichaival can have access to the public APIs. And I haven't enabled No-Fun Mode.
