### ISSUE TITLE
Ichaival not working after update

### ISSUE THREAD

**Issue by EfronC** [Utazukin/Ichaival#60]
I accidentally updated Ichaival on my tablet, and somehow the newer one does not work anymore: I open the app, a new syncing pop up appears on the lower border of the screen, and seconds later it crashes, I tried to do a Crash log, and got this

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference

-------Stack Trace --------

   com.utazukin.ichaival.ArchiveJson.<init>(SourceFile:114)
   n3.y.a(SourceFile:97)
   k3.m.b(SourceFile:35)
   u3.S.t(SourceFile:315)
   F3.a.n(SourceFile:9)
   W3.J.run(SourceFile:97)
   W3.Q.c0(SourceFile:141)
   W3.C.y(SourceFile:102)
   R1.q.run(SourceFile:117)
   O1.g.run(SourceFile:84)
   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
   java.lang.Thread.run(Thread.java:1012)
-------------------------------

----------- Cause ------------

--------------------------------
```

Sadly, the option to return to an older version does not work, since neither through F-Droid, nor from the apk , let me downgrade the app(Probably unrelated to Ichaival), and uninstalling is not an option since I've a lot of bookmarks, and don't want to lose them(And there is no way to import/export them).

Ichaival: 1.9.0
LANraragi: 0.9.0
Tablet: Samsung Galaxy Tab A9+
Android: 14

**Comment by Utazukin** [comment]
It looks like there was an issue with the missing summary field.  This will be fixed in the next version.  Updating LANraragi to 0.9.10 or above should also fix it.
